In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('sales.csv')

In [3]:
data

# date -> 0-12 months, 0-3 years, drop unnamed.

,Unnamed: 0,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday,sales
0,425390,366,4,2013-04-18,517,1,0,0,0,4422
1,291687,394,6,2015-04-11,694,1,0,0,0,8297
2,411278,807,4,2013-08-29,970,1,1,0,0,9729
3,664714,802,2,2013-05-28,473,1,1,0,0,6513
4,540835,726,4,2013-10-10,1068,1,1,0,0,10882
...,...,...,...,...,...,...,...,...,...,...
640835,359783,409,6,2013-10-26,483,1,0,0,0,4553
640836,152315,97,1,2014-04-14,987,1,1,0,0,12307
640837,117952,987,1,2014-07-07,925,1,0,0,0,6800
640838,435829,1084,4,2014-06-12,725,1,0,0,0,5344
640839,305711,695,7,2015-05-03,0,0,0,0,0,0

In [4]:
# Sales -> dependant variable
# 
data.columns

Index(['Unnamed: 0', 'store_ID', 'day_of_week', 'date', 'nb_customers_on_day',
       'open', 'promotion', 'state_holiday', 'school_holiday', 'sales'],
      dtype='object')

In [5]:
data['date'] = pd.to_datetime(data['date'])
data['year'] = pd.to_datetime(data['date']).dt.year
data['month'] = pd.to_datetime(data['date']).dt.month
data
data.groupby(['open','state_holiday','school_holiday', 'day_of_week'])['index'].agg(['count'])

KeyError: 'Column not found: index'

In [ ]:
data['year'].unique()
data['state_holiday'] = data['state_holiday'].apply(lambda x: 1 if x in ['a', 'b', 'c'] else 0)
data['state_holiday'].unique()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
# Assuming 'data' is your DataFrame containing the relevant columns

# Extracting predictor and target variables
x = data[['day_of_week', 'nb_customers_on_day', 'open', 'promotion', 'state_holiday', 'school_holiday','month']]
y = data[['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[['day_of_week', 'nb_customers_on_day', 'open', 'promotion', 'state_holiday', 'school_holiday','month']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data['sales'], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

In [ ]:

# Extracting predictor and target variables
x = data[['day_of_week', 'nb_customers_on_day', 'open', 'promotion', 'state_holiday', 'school_holiday','month']]
y = data[['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[['day_of_week', 'nb_customers_on_day', 'open', 'promotion', 'state_holiday', 'school_holiday','month']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data['sales'], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

In [ ]:

# Extracting predictor and target variables
x = data[['nb_customers_on_day','open','promotion']]
y = data[['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[['nb_customers_on_day','open','promotion']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data['sales'], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

In [ ]:

# Extracting predictor and target variables
x = data[['nb_customers_on_day','open','promotion','month']]
y = data[['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[['nb_customers_on_day','open','promotion','month']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data['sales'], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

In [ ]:

# Extracting predictor and target variables
x = data[['day_of_week', 'open', 'promotion']]
y = data[['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[['day_of_week', 'open', 'promotion']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data['sales'], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

In [ ]:
# Extracting predictor and target variables
x = data[data['open']==1][['day_of_week', 'nb_customers_on_day','promotion', 'state_holiday', 'school_holiday','month']]
y = data[data['open']==1][['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[data['open']==1][['day_of_week', 'nb_customers_on_day', 'promotion', 'state_holiday', 'school_holiday','month']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data[data['open']==1][['sales']], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

In [ ]:
# Extracting predictor and target variables
x = data[data['open']==1][['day_of_week', 'nb_customers_on_day','promotion', 'state_holiday', 'school_holiday']]
y = data[data['open']==1][['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[data['open']==1][['day_of_week', 'nb_customers_on_day','promotion', 'state_holiday', 'school_holiday']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data[data['open']==1][['sales']], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

# KNN Model

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 1)
from sklearn.preprocessing import MinMaxScaler
import numpy as np
scaler = MinMaxScaler()

scaler = scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
# create knn model
knnr = KNeighborsRegressor(n_neighbors = 3,weights='distance')

# Train the knn model
model = knnr.fit(X_train, y_train)
y_pred = knnr.predict(X_test)
y_pred
np.array(y_test)
# Predict and score the model
knnr.score(X_test, y_test)

# Lineal regression with test and train

In [ ]:

# Extracting predictor and target variables
x = data[['nb_customers_on_day','open','promotion']]
y = data[['sales']]

# Initializing and fitting the model
model = LinearRegression()
result = model.fit(x, y)

# Printing intercept and coefficients
print("Intercept:", result.intercept_)
print("Coefficients:", result.coef_)

# Calculating the regression line
regression_line = result.predict(x)

# Plotting
#plt.plot(y, regression_line, c='orange')
#plt.scatter(y, x)  # You might want to specify which column of 'x' to scatter against 'y'
#plt.xlabel('Sales')
#plt.ylabel('Predicted Sales')
#plt.show()

y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)
print(r_squared)

# Your response here. 
import statsmodels.api as sm
# Agregar una constante al predictor (intercepto)
X = sm.add_constant(data[['nb_customers_on_day','open','promotion']])

# Ajustar el modelo de regresiÃ³n lineal mÃºltiple
model = sm.OLS(data['sales'], X).fit()

# Obtener un resumen completo
summary = model.summary()
print(summary)
# p-valores inferiores a 0.05, Adj. R-squared cercano a 1. Modelo robusto

# Create linear regression
regr = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 1)
# Train the linear regression
model = regr.fit(X_train, y_train)

# Score the model
model.score(X_test, y_test)

model.predict(X_test)
np.array(y_test)

np.sqrt(((regr.predict(X_test)-np.array(y_test))**2).sum()/len(X_test))

model.coef_


#ridge tries to control the coefficients
from sklearn.linear_model import Ridge

# Create linear regression
regr = Ridge(alpha=1.0)

# Train the linear regression
model = regr.fit(X_train, y_train)

# Score the model
model.score(X_test, y_test)

In [125]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state = 1)
from sklearn.preprocessing import MinMaxScaler
import numpy as np
scaler = MinMaxScaler()

scaler = scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
# create knn model
knnr = KNeighborsRegressor(n_neighbors = 3,weights='distance')

# Train the knn model
model = knnr.fit(X_train, y_train)
y_pred = knnr.predict(X_test)
y_pred
np.array(y_test)
# Predict and score the model
knnr.score(X_test, y_test)

0.8205288613428635

In [126]:
y_pred = knnr.predict(X_test)
y_pred

array([[ 6314.66666667],
       [11357.        ],
       [    0.        ],
       ...,
       [ 8565.66666667],
       [ 6422.33333333],
       [ 8022.66666667]])

In [6]:
import pandas as pd
import pickle
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


# Assuming x and y are your predictor and target variables respectively
x = data[[ 'nb_customers_on_day', 'open', 'promotion']]
y = data['sales']

# Initialize your model
model = LinearRegression()

# Train your model
model.fit(x, y)

# Make predictions
predictions = model.predict(x)

# Save the trained model
with open('model_v0.pkl', 'wb') as file:
    pickle.dump(model, file)

# 3. Save Output to File
# Combine predictions with index and save to a CSV file
output_df = pd.DataFrame({'index': data.index, 'prediction': predictions})
output_df.to_csv('output.csv', index=False)

# 4. Save Model and Feature Engineering
# Save model and feature engineering steps (already done above)

In [7]:
test = pd.read_csv('validation_for students.csv')
x_test = test[[ 'nb_customers_on_day', 'open', 'promotion']]
x_test

       nb_customers_on_day  open  promotion
0                        0     0          0
1                        0     0          0
2                      657     1          1
3                      862     1          0
4                      591     1          1
...                    ...   ...        ...
71200                    0     0          0
71201                    0     0          0
71202                  648     1          0
71203                  626     1          1
71204                  828     1          1

[71205 rows x 3 columns]

In [8]:

import pandas as pd
import pickle


with open('model_v0.pkl', 'rb') as file:
    model = pickle.load(file)


new_data = pd.read_csv('validation_for students.csv')

x_new_data = new_data[['nb_customers_on_day', 'open', 'promotion']]


y_pred_new = model.predict(x_new_data)


y_pred_new

array([ -86.61390605,  -86.61390605, 7053.45075243, ..., 5664.39868933,
       6864.946381  , 8093.26518838])

In [9]:
predictions_df = pd.DataFrame({'Index': new_data['index'], 'Prediction': y_pred_new})


predictions_df.to_csv('predictions_new_data.csv', index=False)

In [10]:
new_data

,index,store_ID,day_of_week,date,nb_customers_on_day,open,promotion,state_holiday,school_holiday
0,272371,415,7,01/03/2015,0,0,0,0,0
1,558468,27,7,29/12/2013,0,0,0,0,0
2,76950,404,3,19/03/2014,657,1,1,0,0
3,77556,683,2,29/01/2013,862,1,0,0,0
4,456344,920,3,19/03/2014,591,1,1,0,0
...,...,...,...,...,...,...,...,...,...
71200,59062,441,7,26/10/2014,0,0,0,0,0
71201,687449,377,7,18/08/2013,0,0,0,0,0
71202,207393,15,3,11/06/2014,648,1,0,0,0
71203,233378,950,2,23/04/2013,626,1,1,0,0
71204,85695,932,4,21/11/2013,828,1,1,0,0